using System.ComponentModel.DataAnnotations;
using System.Net;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
using Microsoft.AspNetCore.Mvc;

namespace CulinaryBlog.API.Controllers;

/// <summary>Request to generate an assistant response from a conversation.</summary>
public sealed record OpenAiChatRequest
{
    [Required]
    public required string ApiKey { get; init; }

    [Required, MinLength(1), MaxLength(20)]
    public required IReadOnlyList<OpenAiChatMessage> Messages { get; init; }
}

/// <summary>A single user or assistant message in the conversation.</summary>
public sealed record OpenAiChatMessage
{
    [Required, RegularExpression("^(user|assistant)$")]
    public required string Role { get; init; }

    [Required, MaxLength(12000)]
    public required string Content { get; init; }
}

/// <summary>Text generated by OpenAI.</summary>
public sealed record OpenAiChatResponse(string Answer);

[Route("api/openai")]
[ApiController]
public sealed class OpenAIController(IHttpClientFactory httpClientFactory) : ControllerBase
{
    [HttpPost("chat")]
    [ProducesResponseType<OpenAiChatResponse>(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status429TooManyRequests)]
    [ProducesResponseType(StatusCodes.Status502BadGateway)]
    [ProducesResponseType(StatusCodes.Status504GatewayTimeout)]
    public async Task<ActionResult<OpenAiChatResponse>> Chat(
        [FromBody] OpenAiChatRequest request,
        CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(request.ApiKey) || request.Messages.Count == 0)
        {
            return BadRequest(new { message = "Cần có API key và ít nhất một tin nhắn." });
        }

        using var upstreamRequest = new HttpRequestMessage(HttpMethod.Post, "https://api.openai.com/v1/responses");
        upstreamRequest.Headers.Authorization = new AuthenticationHeaderValue("Bearer", request.ApiKey.Trim());
        upstreamRequest.Content = JsonContent.Create(new
        {
            model = "gpt-5-mini",
            instructions = "You are the Bep Nha assistant. Help with cooking, recipes, ingredients, meal planning, and general questions. Answer clearly in the user's language.",
            input = request.Messages.Select(message => new
            {
                role = message.Role,
                content = message.Content
            }),
            max_output_tokens = 1200
        });

        try
        {
            using var upstreamResponse = await httpClientFactory
                .CreateClient("OpenAI")
                .SendAsync(upstreamRequest, HttpCompletionOption.ResponseHeadersRead, cancellationToken);
            await using var responseStream = await upstreamResponse.Content.ReadAsStreamAsync(cancellationToken);
            using var responseJson = await JsonDocument.ParseAsync(responseStream, cancellationToken: cancellationToken);

            if (!upstreamResponse.IsSuccessStatusCode)
            {
                var message = responseJson.RootElement.TryGetProperty("error", out var error)
                    && error.TryGetProperty("message", out var errorMessage)
                    ? errorMessage.GetString() ?? "OpenAI từ chối yêu cầu."
                    : "OpenAI từ chối yêu cầu.";

                return upstreamResponse.StatusCode switch
                {
                    HttpStatusCode.Unauthorized => Unauthorized(new { message }),
                    HttpStatusCode.TooManyRequests => StatusCode(StatusCodes.Status429TooManyRequests, new { message }),
                    HttpStatusCode.BadRequest => BadRequest(new { message }),
                    _ => StatusCode(StatusCodes.Status502BadGateway, new { message })
                };
            }

            var answerBuilder = new StringBuilder();
            if (responseJson.RootElement.TryGetProperty("output", out var outputItems)
                && outputItems.ValueKind == JsonValueKind.Array)
            {
                foreach (var outputItem in outputItems.EnumerateArray())
                {
                    if (!outputItem.TryGetProperty("content", out var contentItems)
                        || contentItems.ValueKind != JsonValueKind.Array)
                    {
                        continue;
                    }

                    foreach (var contentItem in contentItems.EnumerateArray())
                    {
                        if (contentItem.TryGetProperty("type", out var type)
                            && type.GetString() == "output_text"
                            && contentItem.TryGetProperty("text", out var text))
                        {
                            answerBuilder.Append(text.GetString());
                        }
                    }
                }
            }

            var answer = answerBuilder.ToString().Trim();
            return string.IsNullOrWhiteSpace(answer)
                ? StatusCode(StatusCodes.Status502BadGateway, new { message = "OpenAI không trả về nội dung văn bản." })
                : Ok(new OpenAiChatResponse(answer));
        }
        catch (TaskCanceledException) when (!cancellationToken.IsCancellationRequested)
        {
            return StatusCode(StatusCodes.Status504GatewayTimeout, new { message = "OpenAI mất quá 45 giây để phản hồi. Hãy thử lại." });
        }
        catch (HttpRequestException)
        {
            return StatusCode(StatusCodes.Status502BadGateway, new { message = "Backend không kết nối được tới OpenAI. Kiểm tra mạng rồi thử lại." });
        }
    }
}